version: "3"
services:

  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27018:27018
    command: mongod --port 27018 --logpath=/dev/null # --quiet

  frontend:
    build:
      context: frontend
    ports:
      - "8080:8080"

  backend:
    build:
      context: backend
    ports:
      - "4000:8000"
